/**
 * @Author peerless2012
 * @Email peerless2012@126.com
 * @DateTime 2025/4/26 20:49
 * @Version V1.0
 * @Description
 */
export class Constants {
  /**
   * NavDestination default.
   */
  public static readonly NAV_DESTINATION_DEFAULT: string = 'NavDestination_default';

  /**
   * NavDestination item video.
   */
  public static readonly NAV_DESTINATION_ITEM_VIDEO: string = 'NavDestination_item_video';

  /**
   * NavDestination item payCode.
   */
  public static readonly NAV_DESTINATION_ITEM_PAY_CODE: string = 'NavDestination_item_pay_code';

  /**
   * 100 percent.
   */
  public static readonly FULL_PERCENT: string = '100%';

  /**
   * click set brightness
   */
  public static readonly SET_BRIGHTNESS_CLICK: number = 0;

  /**
   * slide set brightness
   */
  public static readonly SET_BRIGHTNESS_SLIDE: number = 1;
}