/**
 * @Author peerless2012
 * @Email peerless2012@126.com
 * @DateTime 2025/3/19 21:20
 * @Version V1.0
 * @Description
 */
export class FinPages {

  /**
   * Auth page
   */
  public static readonly PAGE_FIN_ADD_SERVER = "FinAuthPage"

  /**
   * Edit server page
   */
  public static readonly PAGE_FIN_EDIT_SERVER = "FinEditServerPage"

  /**
   * Edit address page
   */
  public static readonly PAGE_FIN_EDIT_ADDRESS = "FinEditAddressPage"

  /**
   * Edit user page
   */
  public static readonly PAGE_FIN_EDIT_USER = "FinEditUserPage"

}