import { ThemeMediaResult } from "./ThemeMediaResult";

/**
 *
 * @export
 * @interface AllThemeMediaResult
 */
export interface AllThemeMediaResult {
  /**
   *
   * @type {ThemeMediaResult}
   * @memberof AllThemeMediaResult
   */
  'ThemeVideosResult'?: ThemeMediaResult;
  /**
   *
   * @type {ThemeMediaResult}
   * @memberof AllThemeMediaResult
   */
  'ThemeSongsResult'?: ThemeMediaResult;
  /**
   *
   * @type {ThemeMediaResult}
   * @memberof AllThemeMediaResult
   */
  'SoundtrackSongsResult'?: ThemeMediaResult;
}
