/**
 * Gets or sets the primary image blurhash.
 * @export
 * @interface BaseItemPersonImageBlurHashes
 */
export interface BaseItemPersonImageBlurHashes {
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Primary'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Art'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Backdrop'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Banner'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Logo'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Thumb'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Disc'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Box'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Screenshot'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Menu'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Chapter'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'BoxRear'?: Record<string, string>;
  /**
   *
   * @type {Record<string, string>}
   * @memberof BaseItemPersonImageBlurHashes
   */
  'Profile'?: Record<string, string>;
}
