/**
 * These represent sort orders.
 * @export
 * @enum {string}
 */
export enum ItemSortBy {
  Default='Default',
  AiredEpisodeOrder='AiredEpisodeOrder',
  Album='Album',
  AlbumArtist='AlbumArtist',
  Artist='Artist',
  DateCreated='DateCreated',
  OfficialRating='OfficialRating',
  DatePlayed='DatePlayed',
  PremiereDate='PremiereDate',
  StartDate='StartDate',
  SortName='SortName',
  Name='Name',
  Random='Random',
  Runtime='Runtime',
  CommunityRating='CommunityRating',
  ProductionYear='ProductionYear',
  PlayCount='PlayCount',
  CriticRating='CriticRating',
  IsFolder='IsFolder',
  IsUnplayed='IsUnplayed',
  IsPlayed='IsPlayed',
  SeriesSortName='SeriesSortName',
  VideoBitRate='VideoBitRate',
  AirTime='AirTime',
  Studio='Studio',
  IsFavoriteOrLiked='IsFavoriteOrLiked',
  DateLastContentAdded='DateLastContentAdded',
  SeriesDatePlayed='SeriesDatePlayed',
  ParentIndexNumber='ParentIndexNumber',
  IndexNumber='IndexNumber',
  SimilarityScore='SimilarityScore',
  SearchScore='SearchScore'
}