/**
 * Library option info dto.
 * @export
 * @interface LibraryOptionInfoDto
 */
export interface LibraryOptionInfoDto {
  /**
   * Gets or sets name.
   * @type {string}
   * @memberof LibraryOptionInfoDto
   */
  'Name'?: string | null;
  /**
   * Gets or sets a value indicating whether default enabled.
   * @type {boolean}
   * @memberof LibraryOptionInfoDto
   */
  'DefaultEnabled'?: boolean;
}
