/**
 * PinRedeemResult
 * @export
 * @interface PinRedeemResult
 */
export interface PinRedeemResult {
  /**
   * Gets or sets a value indicating whether this MediaBrowser.Model.Users.PinRedeemResult is success.
   * @type {boolean}
   * @memberof PinRedeemResult
   */
  'Success'?: boolean;
  /**
   * Gets or sets the users reset.
   * @type {Array<string>}
   * @memberof PinRedeemResult
   */
  'UsersReset'?: Array<string>;
}