export interface FinPublicSystemInfo {

  /**
   * Gets or sets the id.
   * @type {string}
   * @memberof PublicSystemInfo
   */
  'Id'?: string | null;

  /**
   * Gets or sets the name of the server.
   * @type {string}
   * @memberof PublicSystemInfo
   */
  'ServerName'?: string | null;

  /**
   * Gets or sets the server version.
   * @type {string}
   * @memberof PublicSystemInfo
   */
  'Version'?: string | null;

  /**
   * Gets or sets a value indicating whether the startup wizard is completed.
   * @type {boolean}
   * @memberof PublicSystemInfo
   */
  'StartupWizardCompleted'?: boolean | null;

}