/**
 * The cast receiver application model.
 * @export
 * @interface CastReceiverApplication
 */
export interface CastReceiverApplication {
  /**
   * Gets or sets the cast receiver application id.
   * @type {string}
   * @memberof CastReceiverApplication
   */
  'Id'?: string;
  /**
   * Gets or sets the cast receiver application name.
   * @type {string}
   * @memberof CastReceiverApplication
   */
  'Name'?: string;
}