/**
 * Enum MetadataFields.
 * @export
 * @enum {string}
 */
export enum MetadataField {
  AlbumArtists= 'AlbumArtists',
  Artists = 'Artists',
  Cast = 'Cast',
  ChannelNumber = 'ChannelNumber',
  Collections = 'Collections',
  CommunityRating = 'CommunityRating',
  Composers = 'Composers',
  CriticRating = 'CriticRating',
  Genres = 'Genres',
  Name = 'Name',
  OfficialRating = 'OfficialRating',
  OriginalTitle = 'OriginalTitle',
  Overview = 'Overview',
  ProductionLocations = 'ProductionLocations',
  Runtime = 'Runtime',
  SortIndexNumber = 'SortIndexNumber',
  SortName = 'SortName',
  SortParentIndexNumber = 'SortParentIndexNumber',
  Studios = 'Studios',
  Tagline = 'Tagline',
  Tags = 'Tags',
}